# Generated by Django 5.1.2 on 2024-11-17 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_spacetravelerprofile_regular_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacetravelerprofile',
            name='regular_account',
        ),
        migrations.RemoveField(
            model_name='spacetravelerprofile',
            name='social_account',
        ),
        migrations.AddField(
            model_name='spacetravelerprofile',
            name='real_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
