# Generated by Django 5.1.2 on 2024-11-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_spacetraveler_security_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacetraveler',
            name='security_question',
            field=models.IntegerField(choices=[(0, 'What was the name of your first pet?'), (1, 'What street did you grow up on?'), (2, "What is your mother's maiden name?"), (3, 'Where was your first date?'), (4, 'What is the name of your best childhood friend?')], null=True),
        ),
    ]
