# Generated by Django 5.1.2 on 2024-12-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stellar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstellationTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("stars", models.CharField(max_length=100)),
                ("about1", models.CharField(max_length=200)),
                ("about2", models.CharField(max_length=200)),
                ("about3", models.CharField(max_length=200)),
                ("length", models.PositiveIntegerField()),
                ("num_people", models.PositiveIntegerField()),
            ],
        ),
    ]
