# Generated by Django 5.1.2 on 2024-12-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stellar", "0002_constellationtour"),
    ]

    operations = [
        migrations.AddField(
            model_name="constellationtour",
            name="image1",
            field=models.ImageField(
                default="static/stellar/constellations/BigDipper.jpg",
                upload_to="static",
            ),
        ),
        migrations.AddField(
            model_name="constellationtour",
            name="image2",
            field=models.ImageField(
                default="static/stellar/constellations/BigDipper.jpg",
                upload_to="static",
            ),
        ),
        migrations.AddField(
            model_name="constellationtour",
            name="image3",
            field=models.ImageField(
                default="static/stellar/constellations/BigDipper.jpg",
                upload_to="static",
            ),
        ),
        migrations.AddField(
            model_name="startour",
            name="image1",
            field=models.ImageField(
                default="static/stellar/constellations/BigDipper.jpg",
                upload_to="static",
            ),
        ),
        migrations.AddField(
            model_name="startour",
            name="image2",
            field=models.ImageField(
                default="static/stellar/constellations/BigDipper.jpg",
                upload_to="static",
            ),
        ),
        migrations.AddField(
            model_name="startour",
            name="image3",
            field=models.ImageField(
                default="static/stellar/constellations/BigDipper.jpg",
                upload_to="static",
            ),
        ),
    ]
