# Generated by Django 5.1.2 on 2024-12-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stellar", "0003_constellationtour_image1_constellationtour_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="constellationtour",
            name="link",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="startour",
            name="link",
            field=models.CharField(default="none", max_length=100),
        ),
    ]
