# Generated by Django 5.1.2 on 2024-11-30 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetary", "0001_initial"),
        migrations.swappable_dependency(settings.STAR_RATINGS_RATING_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planetarytour",
            name="ratings",
            field=models.ManyToManyField(
                blank=True,
                related_name="planetary_tours",
                to=settings.STAR_RATINGS_RATING_MODEL,
            ),
        ),
    ]
