# Generated by Django 5.1.2 on 2024-12-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetary", "0002_planetarytour_ratings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planetarytour",
            name="ratings",
        ),
    ]
