# Generated by Django 4.2.16 on 2024-12-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetary", "0003_remove_planetarytour_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetarytour",
            name="about_planet",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planetarytour",
            name="location_and_orbit",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
