# Generated by Django 5.1.2 on 2024-12-02 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetary", "0003_remove_planetarytour_ratings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlanetaryTour",
        ),
    ]
