# Generated by Django 5.1.2 on 2024-12-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetary", "0005_planetarytour_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetarytour",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="planetary_tours/"
            ),
        ),
        migrations.AddField(
            model_name="planetarytour",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="planetary_tours/"
            ),
        ),
        migrations.AddField(
            model_name="planetarytour",
            name="image4",
            field=models.ImageField(
                blank=True, null=True, upload_to="planetary_tours/"
            ),
        ),
    ]
