# Generated by Django 5.1.2 on 2024-12-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetary", "0004_delete_planetarytour"),
        ("planetary", "0006_planetarytour_image2_planetarytour_image3_and_more"),
    ]

    operations = []
