# Generated by Django 5.1.2 on 2024-12-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("planetary", "0007_merge_20241203_1359"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanetaryTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_and_orbit", models.TextField()),
                ("about_planet", models.TextField()),
                ("name", models.CharField(max_length=100)),
                ("length", models.PositiveIntegerField()),
                ("num_people", models.PositiveIntegerField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="planetary_tours/"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="planetary_tours/"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="planetary_tours/"
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True, null=True, upload_to="planetary_tours/"
                    ),
                ),
            ],
        ),
    ]
