# Generated by Django 5.1.2 on 2024-12-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetary", "0008_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetarytour",
            name="link",
            field=models.CharField(default="none", max_length=100),
        ),
    ]
